version: '3.8'

# networks:
#   backend:
#     driver: bridge
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - $DB_PORT:$DB_PORT
    expose:
      - $DB_PORT
    # networks:
    #   - backend
  back:
    depends_on:
      - mysqldb
    build:  ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - DB_PORT=$DB_PORT
    # networks:
    #   - backend
    links:
      - mysqldb
  migration:
    build:
      context: .
    command: ["./wait-for-it/wait-for-it.sh", "mysqldb:3306", "--", "npm", "run", "migrate"]
    links:
      - mysqldb
    depends_on:
      - mysqldb
